# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'web_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtWidgets import QDialog


class UiWebView:
    __dialog: QDialog

    def __init__(self):
        self.__dialog = QDialog()
        self.__dialog.setObjectName("Dialog")
        self.__dialog.resize(425, 394)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.__dialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 340, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel| QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.webView = QWebEngineView(self.__dialog)
        self.webView.setGeometry(QtCore.QRect(20, 30, 381, 281))
        self.webView.setUrl(QtCore.QUrl("file:///home/denis/Documents/university/3kurs2sem/Security/lab2/index1.html"))
        self.webView.setObjectName("webView")
        self.buttonBox.accepted.connect(self.__dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(self.__dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self.__dialog)

    def exec(self) -> int:
        self.webView.show()
        return self.__dialog.exec_()
