# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtCore import QRect, QMetaObject, QCoreApplication
from PyQt5.QtWidgets import QWidget, QGridLayout, QPushButton, QMenuBar, QStatusBar, QTableView

PROGRAM_NAME = "RedRose"


class UiMainWindow(QWidget):

    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(923, 578)
        self.centralwidget = QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QRect(710, 30, 191, 471))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_locate_gaps = QPushButton(self.gridLayoutWidget_2)
        self.button_locate_gaps.setObjectName("button_locate_gaps")
        self.gridLayout_2.addWidget(self.button_locate_gaps, 1, 0, 1, 1)
        self.button_safe_db = QPushButton(self.gridLayoutWidget_2)
        self.button_safe_db.setObjectName("button_safe_db")
        self.gridLayout_2.addWidget(self.button_safe_db, 3, 0, 1, 1)
        self.button_import_files = QPushButton(self.gridLayoutWidget_2)
        self.button_import_files.setObjectName("button_import_files")
        self.gridLayout_2.addWidget(self.button_import_files, 0, 0, 1, 1)
        self.button_fill_gaps = QPushButton(self.gridLayoutWidget_2)
        self.button_fill_gaps.setObjectName("button_fill_gaps")
        self.gridLayout_2.addWidget(self.button_fill_gaps, 2, 0, 1, 1)
        self.button_export_files = QPushButton(self.gridLayoutWidget_2)
        self.button_export_files.setObjectName("button_export_files")
        self.gridLayout_2.addWidget(self.button_export_files, 4, 0, 1, 1)
        self.tableView = QTableView(self.centralwidget)
        self.tableView.setGeometry(QRect(20, 30, 671, 471))
        self.tableView.setObjectName("tableView")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(main_window)
        self.menubar.setGeometry(QRect(0, 0, 923, 32))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.retranslateUi(main_window)
        QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QCoreApplication.translate
        main_window.setWindowTitle(_translate(PROGRAM_NAME, PROGRAM_NAME))
        self.button_locate_gaps.setText(_translate(PROGRAM_NAME, "Locate data gaps"))
        self.button_safe_db.setText(_translate(PROGRAM_NAME, "Safe to database"))
        self.button_import_files.setText(_translate(PROGRAM_NAME, "Import excel files"))
        self.button_fill_gaps.setText(_translate(PROGRAM_NAME, "Fill gaps"))
        self.button_export_files.setText(_translate(PROGRAM_NAME, "Export excel file"))
